// <auto-generated />
using System;
using FA.JustBlog.Core.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FA.JustBlog.Core.Migrations
{
    [DbContext(typeof(BlogContext))]
    [Migration("20231130015324_AddPostView")]
    partial class AddPostView
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FA.JustBlog.Core.Models.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("View")
                        .HasColumnType("int");

                    b.HasKey("PostId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            Content = "This is my first post",
                            CreatedDate = new DateTime(2023, 11, 30, 8, 53, 24, 233, DateTimeKind.Local).AddTicks(3796),
                            Title = "Post 1",
                            View = 100
                        },
                        new
                        {
                            PostId = 2,
                            Content = "This is my first post",
                            CreatedDate = new DateTime(2023, 11, 30, 8, 53, 24, 233, DateTimeKind.Local).AddTicks(3813),
                            Title = "Post 3",
                            View = 95
                        },
                        new
                        {
                            PostId = 3,
                            Content = "This is my first post",
                            CreatedDate = new DateTime(2023, 11, 30, 8, 53, 24, 233, DateTimeKind.Local).AddTicks(3815),
                            Title = "Post 4",
                            View = 20
                        },
                        new
                        {
                            PostId = 4,
                            Content = "This is my first post",
                            CreatedDate = new DateTime(2023, 11, 30, 8, 53, 24, 233, DateTimeKind.Local).AddTicks(3816),
                            Title = "Post 5",
                            View = 50
                        },
                        new
                        {
                            PostId = 5,
                            Content = "This is my first post",
                            CreatedDate = new DateTime(2023, 11, 30, 8, 53, 24, 233, DateTimeKind.Local).AddTicks(3816),
                            Title = "Post 2",
                            View = 111
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
